### ISSUE TITLE
Custom scalars

### ISSUE THREAD

**Issue by Teddy-Schmitz** [vektah/gqlgen#1]
Hi,

I am trying to figure out how to use custom scalars with this library, I added it to types.json and I'm still getting a "panic: unknown scalar".  Looking at the code it wasn't immediately apparent how to do this.

Thanks!

**Comment by vektah** [comment]
It wasn't immediately required so I haven't added it yet. It should be pretty easy to add, what kind of custom scalars were you looking to define?

**Comment by Teddy-Schmitz** [comment]
We have custom scalars for the postgres json type and a few other special map and string types that we are using in our application.

**Comment by vektah** [comment]
see [the new example](https://github.com/vektah/gqlgen/tree/master/example/scalars)
