### ISSUE TITLE
Generated code ends up being invalid when using keywords as parameters

### ISSUE THREAD

**Issue by ameliaikeda** [vektah/gqlgen#101]
### Expected Behaviour

Running `gqlgen -schema schema.graphql` (below) should correctly generate models and scaffolding to use this library

### Actual Behavior

Right after generating code, `gofmt` chokes pretty hard on the generated code, specifically this line:

```
Mutation_tokenExchange(ctx context.Context, token string, type *TokenType) (*Token, error)
```

The error here is `type *TokenType` not being valid go, throwing `generated.go:<line>:<col>: expected 'IDENT', found 'type'`.

Is there any way defined for dealing with top-level go keywords, aside from "don't use them"?

### Minimal graphql.schema and models to reproduce

```
type Mutation {
  tokenExchange(
    # The token to exchange.
    token: String!

    # The type of token provided.
    type: TokenType
  ): Token
}

# An auth token
type Token {
  # The token ID
  id: String!
}

# A token type
enum TokenType {
  FOO
  BAR
}
```

**Comment by vektah** [comment]
Interesting. It should be a pretty easy fix, but what should the output be? append an underscore?

**Comment by ameliaikeda** [comment]
I think it probably should be; we don't want to have to change the schema at all imo, but we could maybe keep an array of reserved words to underscore/alter?
