### ISSUE TITLE
Regeneration Fails with `MakeExecutableSchema`

### ISSUE THREAD

**Issue by JackyChiu** [vektah/gqlgen#112]
### Expected Behavior
```bash
# generated.go & model_gen.go already exists
# methods from generated.go are in use

gqlgen -schema schema.graphql

# recreates the generated.go
# recreates the model_gen.go
```

### Actual Behavior
```bash
# generated.go & model_gen.go already exists
# methods from generated.go are in use

gqlgen -schema schema.graphql

$GOPATH/src/github.com/foo/bar/file.go:1:1: undeclared name: MakeExecutableSchema
exec plan failed: loading failed: couldn't load packages due to errors: github.com/foo/bar
```
### Minimal graphql.schema and models to reproduce
```
schema {
  query Query
}

type Query {
  foo(): Int
}
```

And have `MakeExecutableSchema` used by another file. 

### Details
Regeneration of schemas are failing because of `MakeExecutableSchema` not being available (after the generation first deletes the `model_gen.go` and `generated.go`. This leads to the hack of having to comment out the line that uses `MakeExecutableSchema` every time before running the generation.

I'm going to take a look at the implementation and we can discuss a nice solution to this?

**Comment by JackyChiu** [comment]
Looks like it's causing by the `bind` phase, where gqlgen loads the program and doesn't allow for errors: https://github.com/vektah/gqlgen/blob/3990eacf7d8d99143a69b249ef164787ed00e2ee/codegen/build.go#L61.

I'm not too sure how the `bind` could be built without the program being loaded.

**Comment by vektah** [comment]
Yeah, putting the handler in the same package as the generated code causes that package to be uncompilable.

I usually work around this by moving the handler (wherever you call MakeExecutableSchema) out of the package. check the examples for a demo.

I'm not sure there's a better way to handle it, but there really shouldn't be any errors during that final phase and its likely that errors could generate invalid code.Thoguhts?

**Comment by JackyChiu** [comment]
I like the idea of having a separate package for resolvers/generated code. But I can also see that being a blocker for someone starting a project and not being aware. 

I don't quite understand why the generated code depends on the existing code. For example with protobuf I can write the DSL and have the Go code generated without worrying about the existing program. Do you mind explaining?

**Comment by vektah** [comment]
Protobuf doesn't look at any of your existing code, it only generates. gqlgen looks at your existing types and reuses them, to do that the packages referenced by the runtime must be valid without it.  I think this is one of the key advantages of gqlgen, because it removes all the boilerplate mapping onto your database types but it comes at the cost of having to take a little care when structuring your packages. There's probably room for improvement here in the docs and error messages, and maybe in the way the statc analyser works.
