### ISSUE TITLE
Proposed BC break - always generate all fields on models

### ISSUE THREAD

**Issue by vektah** [vektah/gqlgen#117]
Currently 
```graphql
type Foo {
    name: String
    Bars: [Bar!]!
}
```

Will generate:
```go
type Foo struct {
    Name string
    BarId int // instead of Bars []Bar
}
```

Does anyone rely on this behaviour? Can we generate `Bars []Bar` instead?

**Comment by dvic** [comment]
I'd go for an approach where you can customize the automatically generated structs. We often have a mix of 'embedded' objects (which can be directly served) and object references (ID's). We would need to be able to configure two things:
  * Disable generating Go fields for certain GraphQL fields (e.g., `Foo.Bars`)
  * Add additional Go fields to the generated structs (e.g., `Foo.BarID`)

This way, we can have mixed embedded and reference objects while remaining backwards compatible (you can setup the defaults in such a way that the current situation does not change).

**Comment by vektah** [comment]
This has shipped, if you were relying on this feature you will need to copy the model out and add it to your types.json.

Future work with directives will make it easier to customise model generation.
