### ISSUE TITLE
Use goreleaser

### ISSUE THREAD

**Issue by iamclaytonray** [vektah/gqlgen#119]
The issue template is irrelevant, so I deleted it. Would it be beneficial to use [goreleaser](https://goreleaser.com/)? If so, I can shoot a PR over

**Comment by vektah** [comment]
The hard part here isn't building a binary, its making sure the generated code is importing the same version of gqlgen that was used to generated it.

Using [gorunpkg](https://gqlgen.com/getting-started/#finishing-touches) means you don't need to install the binary at all, just use the one in vendor so they can never be out of sync.

Maybe there could be a separate binary that does [Skeleton generation](https://github.com/vektah/gqlgen/issues/9) and sets up dep correctly then calls into gqlgen to do the generation?
