### ISSUE TITLE
Use without net/http

### ISSUE THREAD

**Issue by akaytatsu** [vektah/gqlgen#129]
In my project, i use revel framework (http://revel.github.io), so, this is not the question. 

always, the example is:

http.Handle("/query", handler.GraphQL(
		todo.MakeExecutableSchema(todo.New()),
		handler.RecoverFunc(func(ctx context.Context, err interface{}) error {
			// send this panic somewhere
			log.Print(err)
			debug.PrintStack()
			return errors.New("user message on panic")
		}),
	))

But the Revel (or others frameworks like beego) not use net/http.

In this case, how i use gqlgen?

**Comment by vektah** [comment]
This isn't a place to get help with revel, here is the [FAQ](https://revel.github.io/manual/faq.html#how-do-i-integrate-existing-httphandlers-with-revel-)

> But the Revel (or others frameworks like beego) not use net/http.

Yeah, I think most people chose not to use a framework when its so easy to grab some good libraries and compose them. eg
 - https://github.com/go-chi/chi
 - https://github.com/go-gorp/gorp
 - https://github.com/gorilla/sessions

You would be 90% of the way to a "framework" without ditching http handlers.
