### ISSUE TITLE
Schema in multiple files

### ISSUE THREAD

**Issue by tkallioras** [vektah/gqlgen#131]
Is there a way to have the schema spread out in multiple files? In large code bases having one large file might become difficult to maintain.

**Comment by DenisNeustroev** [comment]
run the script before your build process (maybe using go generate or Makefile)

schema.sh
```bash
for f in ./graphql/schema/*.gql; do cat $f; echo; done > ./graphql/schema_generated.gql
```

**Comment by vektah** [comment]
I'm hoping to add support for [graphql-import syntax](https://github.com/prismagraphql/graphql-import) into the [new parser](https://github.com/vektah/gqlparser) (until something lands in a spec).

**Comment by vektah** [comment]
Closing in favour of https://github.com/vektah/gqlgen/issues/6
