### ISSUE TITLE
Viewer schema type

### ISSUE THREAD

**Issue by ArkadyB** [vektah/gqlgen#132]
Hi, thank you for the lib!

I have problems understanding how can i retrieve data for my Viewer object based schema.
My top level schema object is Query -> Viewer with anythin else going below Viewer.

Say i have:
```
query{
       viewer{
            id
            name
            group{
               id 
               name
            }
            viecles{
               id 
               name
            }
       }
}
```

Where user information is read with UserService and viecles list is returned by VieclesService. 
How do i based on request data call only respective resolvers?

**Comment by vektah** [comment]
Request data lives in context, here's an older related issue https://github.com/vektah/gqlgen/issues/98.

Lots of things are going to need the viewer for permission checks, so do it once up front and out it in context.

**Comment by ArkadyB** [comment]
@vektah do u mean i should manually parse incoming request and resolve pieces as required?

**Comment by vektah** [comment]
Of course not 😒 

Put the user in context:
```golang
func UserMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		user := findUserForRequest(r)
		ctx := context.WithValue(r.Context(), "USER", user)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```

and then in the viewer resolver pull it out again:
```golang
func (r *Resolvers) Query_viewer(ctx context.Context) (my.User, error) {
    return ctx.Value("USER").(my.User), nil
}
```

**Comment by vektah** [comment]
Head over to https://gitter.im/gqlgen/Lobby for help, I don't think this is an issue with gqlgen.
