### ISSUE TITLE
How to use gqlgen after commit a5c02e6c1 ?

### ISSUE THREAD

**Issue by burkostya** [vektah/gqlgen#138]
Are there some docs?
ref a5c02e6c1

**Comment by cayter** [comment]
Not directly related, but is there a plan to tag and release using semantic versioning? Thanks. @vektah

**Comment by vektah** [comment]
New change notes are [here](https://github.com/vektah/gqlgen/releases/tag/0.2.0)

If you're still having issues, jump into http://gitter.im/gqlgen/Lobby
