### ISSUE TITLE
docs: Getting start is broken

### ISSUE THREAD

**Issue by vvakame** [vektah/gqlgen#142]
https://gqlgen.com/getting-started/

### Expected Behaviour

I can finish until the end.

### Actual Behavior

Un compile error occured.

### Minimal graphql.schema and models to reproduce

`Resolvers` interface doesn't have `Todo_user` method and `Todo` struct doesn't have `UserID` field... 👀

**Comment by burkostya** [comment]
relates to #138

**Comment by vektah** [comment]
Yeah your on the right track, but A todo probably only has one user:
```
type Todo struct {
	ID     string
	Text   string
	Done   bool
	UserID string
}
```

I wish there was a better way to write those tutorials, such that CI would complain when they broke. So easy to forget about them :-/

Ill run through it and update it.

**Comment by vvakame** [comment]
sounds good!
If there is a missing field, add a method to resolve it to Resolver. 
It seems like a pretty good way. 😸

**Comment by vektah** [comment]
https://gqlgen.com/getting-started/ is up to date now
