### ISSUE TITLE
Generated code imports own package (import cycle)

### ISSUE THREAD

**Issue by dabfleming** [vektah/gqlgen#143]
There may be a way to avoid this using the `package` and `modelpackage` flags, but it isn't obvious to me.

My situation is I'm generating in the `foo/bar/model` package, and types.json includes `"Form": "foo/bar/model.Form"`

### Expected Behaviour

Generator recognizes this is the destination package, does not attempt import.

### Actual Behavior

generated.go includes import line: ` "foo/bar/model"` resulting in import cycle.

**Comment by z0mbie42** [comment]
a simple schema to reproduce the bug:
```graphql
input Filter {
  offset: Int!
  limit: Int!
}

type Todo {
  id: String!
  text: String!
  author: User!
  events(filter: Filter = {offset: 0, limit: 25}): [Event!]!
}
```

**Comment by JonLundy** [comment]
@z0mbie42 i filled in some of the missing items i see a interesting bug with Filter. 

```go
input Filter {
  offset: Int!
  limit: Int!
}

type Todo {
  id: String!
  text: String!
  author: User!
  # the default value cause a bug
  events(filter: Filter = {offset: 0, limit: 25}): [Event!]!
}

type User {
  name: String!
}

type Event {
  name: String!
}

type Query {
  todos: [Todo!]!
} 
```
generates the following:
```
			var tmp interface{} = map[string]interface{}{"offset":0"limit":25}
```

there is a missing comma between the offset and limit.

**Comment by vektah** [comment]
Thanks for the defaults fix.

The import loop is less obvious, most of the examples work the way you're describing. eg https://github.com/vektah/gqlgen/blob/master/example/scalars/types.json#L2

I wonder if this is another case sensitivity issue, what OS are you running? Have you tried since https://github.com/vektah/gqlgen/pull/136?

A more complete example would be handy here.

**Comment by z0mbie42** [comment]
The simpler way to reproduce the error is using the following project:
https://github.com/z0mbie42/goes/blob/master/_examples/api
 and replace https://github.com/z0mbie42/goes/blob/master/_examples/api/schema.graphql#L14
```graphql
 events(filter: Filter): [Event!]!
```
by
```graphql
events(filter: Filter = {offset: 0, limit: 25}): [Event!]!
```

But, after applying the patch #146 the code generate without error (no missing comma and no import cycle)
