### ISSUE TITLE
Data validators - question

### ISSUE THREAD

**Issue by gedw99** [vektah/gqlgen#148]
What's the plan for validators ?

With a model driven architecture it seems ripe to be able to describe alot of validation aspects in the model.

Wondering if anyone know of the Apollo group or others standardising in this yet.

**Comment by vektah** [comment]
You should be able to plug any validation library in you want for models your binding to. I guess this is more about the generated models though?

**Comment by gedw99** [comment]
thanks @vektah for getting back to me. Yeah your right. I was thinking that its possible to generate the validators since we have a fair bit of meta data in the GraphQL schema.
But we cant extedn the GraphQL schema design and add it there, but yeah i guess we can code generate some scaffolding.

First thing is where would you do the Validation ? Lets take an easy example of a Forms based app where your filling out a form and you need to make sure that:
- an Email is a real email ( so thats a single field)
- a Country field and a State filed correlate in that te State exists in that country ( so thats a combination fo two field)
- a Product your ordering really exists in the system ( so thats a check on a different sub system )

where is it done ? Well depends on if your using CQRS / Event source of whatever but lets assume its on the server where you hae access to all the information you need to validate things.
I will say that often you end up splitting validation and you do some on the client and some on the server ( like checking the Product is not out of stock). But lets leave that for now.

So in the types generated is where you want to do field level validation and this can maybe be generated ( like is it an email ) or is it mandatory, but the other two cant be generated like is it a state in a country or is the product out of stock.

**Comment by gedw99** [comment]
yeah i am exploring the code gen aspects of it.
I recall there are some golang validation libs out there that support
codegen too i think.. Cant look now as have to run...

**Comment by vektah** [comment]
There isn't anything that can be actioned on here, use https://gitter.im/gqlgen/Lobby for discussion
