### ISSUE TITLE
Planning for directive support

### ISSUE THREAD

**Issue by vektah** [vektah/gqlgen#156]
Once the new parser lands and we get full support for directives. These things don't need to be in the core runtime, and should be implementable outside. This probably means codegen hooks.

Possible uses:

### `@resolver`
A way to force creating a resolver method for a field, eg
```graphql
type User {
    name @resolver
}
```
would generate a Name resolver even if the user struct has a Name field.

### `@rest`, `@grpc`, `@swagger`
These would implement the resolver method for you by binding to an external API.
```graphql
type Query {
    user(id: Int!): User @grpc(accounts:"foo.bar", method:"GetUsers")
}
```
### `@hasRole`, `@isAdmin`, `@isAuthenticated`
These act as middleware filters, and should be able block calling the resolver
```graphql
type Mutation {
    banUser(id: Int!): User @isAdmin
}
```

### `@resolveString` and all of the [graphql-cats](https://github.com/graphql-cats/graphql-cats) directives
They shouldn't be part of the core, but a way to implement them to test against cats is really high on my list.

### `@skip` and `@include`
these are both runtime directives, not schema but there is probably some overlap here and its worth thinking about them.

These are the ones I want. What do you want to see? Lets collect some ideas before rushing into an implementation.

### `@connection`?
Is there some codegen hook that would make dealing with relay style connections easier?

**Comment by vvakame** [comment]
My team really needs this feature ASAP 🤣
I want to use `@isResourceOwner` and `@isStaff` on `QUERY | FIELD`.
so, Is there anything I can do for you? 🌹

**Comment by sergeyvlakh** [comment]
`@skip/@include` :+1: :+1: :+1:

**Comment by ntucker** [comment]
@skip and @include are both key for using relay-modern effectively.

**Comment by vvakame** [comment]
https://github.com/vektah/gqlgen/pull/130#issuecomment-404762711
vektah said
> The new parser is nearly done now, full directive support should only be a few weeks away.

**Comment by andy9775** [comment]
Would it be possible to write our own directives like in [Apollo](https://www.apollographql.com/docs/graphql-tools/schema-directives.html)?

**Comment by mathewbyrne** [comment]
@andy9775 yes we are currently planning to make directives work much the same as resolvers currently do; directives found in a schema will be generated and you will be able to supply your own implementation.

**Comment by vektah** [comment]
I've broken these out into smaller cards on the 1.0 board
