### ISSUE TITLE
request: process arbitrary fields by resolver

### ISSUE THREAD

**Issue by vvakame** [vektah/gqlgen#161]
I want to process `id: ID!` field by resolver.

[Relay Global Object Identification Specification](https://facebook.github.io/relay/graphql/objectidentification.htm) required `This id should be a globally unique identifier for this object`.
but almost Database is not support that.
GitHub v4 uses something like `echo 010:Repository52265602 | base64` for id.

My app already have `ID` field and It is difficult to change.
so, I want to modify id value by resolver.

I think that it is good to write in types.json like this.

```
{
  "Event": {
    "entity": "github.com/vvakame/foobar.Event",
    "fields": {
      "id": {
        "resolver": true
      }
    }
  }
}
```

I saw #156 and `@resolver` directive.
but I want to use `schema.graphql` to communication between server-side engineer and frontend engineer.
I don't want to expose server-side issue to frontend.

What do you think about this idea?

**Comment by vektah** [comment]
Yeah, a few others have expressed similar sentiments. 

I've been trying not to put any logic into types.json to keep it simple. If we do head down we probably should switch to yaml. It's a pain to support two sets of syntax for this though :disappointed:

Another approach would be to provide a `gqlgen strip-schema` that takes the schema and removes all of its config directives, that doesn't need the service running to easily get a copy.

**Comment by vvakame** [comment]
@vektah I sent a PR that add support to types.yaml 👍 

`gqlgen strip-schema` can not satisfied our team.
because, schema.graphql is modified by server-side engineer and frontend engineer both.
When we want to change GraphQL schema, modify it & sending PR and review each other, make consensus.
