### ISSUE TITLE
Scalable subsciptions proposal

### ISSUE THREAD

**Issue by gedw99** [vektah/gqlgen#164]
I saw the PR for the Websockets subscription support but from what i can see there is not code or plan for how they are going to be managed.

NATS is a golang highly horizontally scalable solution. 500k to 800 k concurrent on just a decent laptop is possible. Its fast.

SO this looks promising.
https://github.com/cdmbase/graphql-nats-subscriptions

TO be honest i am not sure of the logic required to make a query subscription work. I am used to use  REST and letting the user opt to subscribe to a REST endpoint. The endpoint you subscribe to is a ViewModel ( like graphql in a way). So with a event sourced system when a mutation comes in, the commands run and Read only ViewModels / Materialised views get updated and the events that updated the View model are PUSHED back to the Client, and so he can simple update hsi cached copy or react in whatever way he needs. 99% of the time he just makes the exact same change to his ViewModel. This is because the Client is dumb in this architecture and have a complete view model for every possible View they need. Its cheap to have viewModels. You can even run it off triggers in a Database that support Materialised VIews ( but i would not do that )
Its important to stress that the Client needs no flux pattern or anything in this architecture.

For the graphql world i am not sure how the mutation of the logic.... If anyone know i would love to get educated...

**Comment by DenisNeustroev** [comment]
Subscriptions are already working well 😅

**Comment by gedw99** [comment]
@DenisNeustroev i do agree. Chat app has it in the schema and is using only demonstrating a single query structure.

**Comment by tv42** [comment]
I would argue that cross-server distribution should *not* be part of this project, and the library should just enable the app to do that however it sees fit. Less bloat and dependencies is good, and one size fits nobody.

The glue between your `Subscription_*` and NATS should be really simple.

**Comment by vektah** [comment]
It sounds like whats really needed here is a good example of using gqlgen and NATS (or some other message bus).

**Comment by vektah** [comment]
There isn't anything that can be actioned on here, use https://gitter.im/gqlgen/Lobby for discussion
