### ISSUE TITLE
Feature: error extensions

### ISSUE THREAD

**Issue by tv42** [vektah/gqlgen#174]
It would be nice if we could set the `extensions` field on errors. Content is app-specific arbitrary JSON. Maybe something like if the `error` returned from a resolver implements `interface { GraphQLExtensions() interface{} }`, add that as the `extensions` field?

http://facebook.github.io/graphql/June2018/#sec-Errors

```
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}
```

**Comment by tv42** [comment]
Using ErrorPresenter is a little short of ideal, because 1) I don't want to reimplement DefaultErrorPresenter and 2) wrapping DefaultErrorPresenter in a json object is not easy, because it's type `error` and `encoding/json`'s rules only let me meaningfully embed structs.

This does NOT work:

```
type MyError struct {
    error
    Extensions interface{}
}
```

**Comment by vektah** [comment]
Reading the current draft spec it looks like your right. Any custom fields should be in extensions now. I'll update that linked pr and add extensions to ResolverError.

http://facebook.github.io/graphql/draft/#sec-Errors
