### ISSUE TITLE
Support to Int64

### ISSUE THREAD

**Issue by rodrigo-brito** [vektah/gqlgen#196]
### Expected Behaviour
-  Use the fields of model with Int64.

There is another way to use the Int64 on resolvers?
Int32 is not sufficient to me in other cases, for IDs it is ok. This is a simple example.

### Actual Behavior
Model: 
```go
type User struct {
	ID            int64     `json:"userID"`
	Name          string    `json:"name"`
	StateID        *int64    `json:"cityID"`
}
```
gqlgen.yml
```yml
models:
  User:
    model: <projecturl>/graphql/user.User
```

```go
type Resolvers {
	...
	Query_user(ctx context.Context, email string) (*user.User, error)
	User_stateID(ctx context.Context, obj *user.User) (*int, error)
	User_userID(ctx context.Context, obj *user.User) (int, error)
}
```

### Minimal graphql.schema and models to reproduce
```graphql
type User {
    # The user's ID
    userID: Int!

    # The user's name
    name: String!

    # The ID of user state
    stateID: Int
}
```

**Comment by vektah** [comment]
`int` is already 64 bit on most systems, are you sure this isn't already working?

**Comment by rodrigo-brito** [comment]
It is possible to create a custom type for it?

**Comment by vektah** [comment]
For sure, have a read of https://gqlgen.com/reference/scalars/#custom-scalars-for-types-you-don-t-control

**Comment by vektah** [comment]
You can write a [custom scalar](https://gqlgen.com/reference/scalars/) right?

**Comment by jacklaaa89** [comment]
How would that work? I can generate new custom scalars.

**Comment by vektah** [comment]
Can't you remap `Int` in the config?
