### ISSUE TITLE
Support non-nullable list items as before

### ISSUE THREAD

**Issue by newellista** [vektah/gqlgen#199]
### Expected Behaviour
```
func (g *GraphQL) Query_users(ctx context.Context) ([]User, error)
```

### Actual Behavior
```
func (g *GraphQL) Query_users(ctx context.Context) ([]*User, error)
```
### Minimal graphql.schema and models to reproduce
```
type Query {
  users: [Users]
}
```

### Notes:

Before https://github.com/vektah/gqlgen/pull/191 this worked correctly.  However, after that PR was merged, it **always** generates the _optional_ form when returning a slice.

I would expect 
```
type Query {
  users: [Users]!
}
```
to return 
```
func (g *GraphQL) Query_users(ctx context.Context) ([]*User, error)
```

while

```
type Query {
  users: [Users]
}
```

should return:
```
func (g *GraphQL) Query_users(ctx context.Context) ([]User, error)
```

**Comment by vektah** [comment]
Did you try
```
type Query {
    user: [Users!]!
}
```

That's a required list of required elements
