### ISSUE TITLE
Passing data between resolvers (Request?)

### ISSUE THREAD

**Issue by andy9775** [vektah/gqlgen#202]
Hey all. I've just switched to this library from the gophers one as it seems like it's more actively maintained. I am missing a feature that the gophers library provided and I'm wondering if I'm missing something, otherwise if we could add it.

In gophers library, it expected a *Resolver struct, or []*Resolver, to be returned from it's query methods whereas here we just return the data([]Users for example). By returning a resolver it allowed me to attach query specific parameters and details which get passed down to the resolver methods. 

```go
func (s *server) Comment(ctx context.Context, args struct{ ID int32 }) *CommentResolver {
	var c Comment
	s.db.Find(&c, args.ID)
	return &CommentResolver{Comment: c, someData: "hello world", db: s.db}
}

type CommentResolver struct {
	Comment  model.Comment
	someData string
	db       *gorm.DB
}

func (c *CommentResolver) ID() *int32 {
	fmt.Println(c.someData) // prints "hello world"
	i := int32(c.Comment.ID)
	return &i
}

```
(Note that in situations where I had to return an array of data, hence an array of `CommentResolvers` I would attach the data to each Comment Resolver in the array.)

As you can see I can pass through `someData` to each comment.

The hacky approach for this library is to create a `map[string]string` for example at the start of the request and add it to the request context. Then pull the map from the context in my Comment method (above) and add the data. Then in my ID method, I would pull from the context and read it.

I'm not too fond of the above solution so I'm wondering if there is a way to share data directly between resolvers or am I missing something??

**Comment by vektah** [comment]
You can do the same thing by adding CommentResolver.

```
models:
  Comment:
    model: github.com/my/app.CommentResolver
```

Usually I'll do this by embedding rather than wrapping, eg:
```
type CommentPresenter struct {
    *other.Comment
    moreData string
}
```

that way gqlgen can bind directly to the properties of comment and you don't need to write all the individual field wrappers.

I probably wouldnt inject the db though, if you need to go back to the db, leave the field off this presenter and youll get a resolver method added for it.

**Comment by andy9775** [comment]
@vektah nevermind I think I've got it. 

Basically we want gqlgen to use CommentResolver as our model where CommentResolver embeds model.Comment. Then we can attach what we want to the CommentResolver (ala the gophers library)

Thanks!
