### ISSUE TITLE
[new feature]/generate model tag

### ISSUE THREAD

**Issue by imiskolee** [vektah/gqlgen#21]
if i has this graphql define

```graphql
type User{
 id : Int!  #user id
 name:String #user name
login_count:Int! #user login count
}
```

its will be generated a golang struct 

```go
type User struct {
 ID int 
Name *string 
Login_count int 
}
```
i want generated to 

```go
type User struct {
 ID int   `gql:"id,desc:'user id'`
Name *string `gql:"name,desc:'user name'"`
Login_count int `gql:"login_count,desc:'user login count'"`
}
```

and attach more info to field tag.

we can return `desc` tag of field when request __schema.

**Comment by vektah** [comment]
What's the use case? 

All of this data and more is already in the schema object, you can fetch it off the generated executable schema `es.Schema()`.

Perhaps mappings need to go from the go struct back to the schema object?

**Comment by pandada8** [comment]
one possible use case is that the generated model may be used directly with [mgo](https://godoc.org/github.com/globalsign/mgo#Query.All) or other database lib, without redefine or edit the struct again.

**Comment by imiskolee** [comment]
@pandada8   dont direct use  graphql layer object for database layer . its really not a good idea. trust me.

**Comment by vektah** [comment]
I'm going to close this out until there is a good concrete use case.

I don't think gqlgen should be generating your database models, it should be binding to them.

**Comment by fr3fou** [comment]
> @pandada8 dont direct use graphql layer object for database layer . its really not a good idea. trust me.

sorry for necro, but how should this be handled, without running into 

- having to write a lot of boilerplate
- "desynchronization" of types (say you add a field, you'd now have to add it in 3 places - domain type, db type, gql type)
