### ISSUE TITLE
Error: decorated type deeper than introspection query

### ISSUE THREAD

**Issue by tkallioras** [vektah/gqlgen#213]
I have a data structure that corresponds to GeoJSON Multipolygon, which is:

`[[[[Float!]!]!]!]!`

However I get the error: `decorated type deeper than introspection query`

I presume it has to do with the nested array. Is there a way to introspect this kind of data structure, without losing introspection on the whole graph?

Here is a type with a field (multipolygon) that produces the issue

```
type GeoJSON {
  type: String!
  boundingbox: [Float!]
  point: [Float!]
  multipoint: [[Float!]!]
  linestring: [[Float!]!]
  multilinestring: [[[Float!]!]!]
  polygon: [[[Float!]!]!]
  multipolygon: [[[[Float!]!]!]!]
}
```

The problem starts on field `multipolygon`. If I erase this, everything works the way it should.

**Comment by vektah** [comment]
I think this is a problem with your client library, what are you using? most introspection queries stop or 4 or 5 levels deep

**Comment by tkallioras** [comment]
@vektah I am using Insomnia. I should file an issue with them then.
