### ISSUE TITLE
Query caching and whitelisting

### ISSUE THREAD

**Issue by vektah** [vektah/gqlgen#22]
hashing incoming queries and caching the document would improve parse times for large queries.

It would also serve as a great point to whitelist allowed queries. 

Open question: how should the whitelist be specified?

Perhaps [Persisted Queries](https://github.com/apollographql/apollo-link-persisted-queries)?

**Comment by salmana1** [comment]
I would be interested to see how hashing/caching the queries would work. 

However, whitelisting queries (persisted queries) defeats the purpose of using GraphQL. On paper it seems like a great idea but it takes away the flexibility of GraphQL.

**Comment by vektah** [comment]
Hashing / caching would be pretty straight forward to implement, but would need to be measured before it lands. I wonder if there are any good graphql benchmark suites out there?

I think persisted queries offer a few big benefits:
 - locking down a graph to have a similar exposure footprint as REST.
 - protecting against malicious users: maybe something like https://github.com/ivome/graphql-query-complexity is probably better suited for public apis.
 - deleting deprecated fields: in a microservice environment knowing who is using what parts of the graph  lets you fail in CI if you remove something thats still in use.

**Comment by andrewmunro** [comment]
Adding complexity somehow to the context object in the resolver would be very nice! We were thinking of implementing some kind of ACL layer that rate limits complexity per user...

I imagine this would tie in to https://github.com/vektah/gqlgen/issues/5 which gives us access to the query in the resolver?

**Comment by gedw99** [comment]
@salmana1 But for security dont yo want 2 things:
1. Before a query is made to know what the user can and cant do. Hence you can restrict the Nav and also restrict the queries they could type in a query IDE.
2. After they make a query, and it hits the server, check each table they are hitting

??

**Comment by imiskolee** [comment]
first, i think cache is a field level or object level feature. its looks like 

```graphql
type Object @cache(10s) {
   id : Int @cache(10s)
   name: String @cache(20s)
   price: @cache(Never)
}
```

in the blow case, we can define a obejct level cache time and field level cache time.

**Comment by vektah** [comment]
Thats a different kind of caching. This issue is for the incoming query objects, not the resolver results

**Comment by vektah** [comment]
I've broken this out on the project board.

**Comment by xzyfer** [comment]
Were persisted queries implemented? 
If so it'd be great to have the featured listed in the readme :)

**Comment by vektah** [comment]
Nope, just caching. Would be pretty easy to add the hooks required to lookup a query by I'd and let the user implement the store
