### ISSUE TITLE
cannot import absolute path

### ISSUE THREAD

**Issue by bipin244** [vektah/gqlgen#231]
When I run gqlgen it shows `cannot import absolute path` error

**Comment by vektah** [comment]
This needs more info. What command did you run? what did your schema / config look like?

**Comment by bipin244** [comment]
I have put example code outside my go/src folder can is possible to run an example from outside of go/ src?

**Comment by vektah** [comment]
All go code must live in gopath, at least until go 1.11 lands (and go modules are used)

**Comment by bipin244** [comment]
Okay thanks for information
