### ISSUE TITLE
Default Args not implemented.

### ISSUE THREAD

**Issue by Teddy-Schmitz** [vektah/gqlgen#25]
Hello,

Thanks again for this library.  It seems that default arguments in the graph schema isn't implemented?

`blockchain(limit: Int = 10): BlockchainConnection!`

Generates code that has limit as `*int` but I would expect it to be an `int` that sets it to 10 or the passed in value.

**Comment by Teddy-Schmitz** [comment]
O and I guess for reference, what I am currently doing is converting a toy project I wrote a few weeks ago using neelance/graph-go to this project before we evaluate switching over our main production application as we like the features this supports.

Thanks again for sharing thisl ibrary!

**Comment by vektah** [comment]
Is the toy project public? If so, would you mind If i linked to it as an example?

**Comment by Teddy-Schmitz** [comment]
thanks for getting this in so quickly, its not public right now but if that changes I'll let you know.
