### ISSUE TITLE
Question: Access selected fields in resolver

### ISSUE THREAD

**Issue by jbub** [vektah/gqlgen#27]
Hello, first thank you for a great project! Great job!

I have a question, say i am using postgres as my datasource for resolvers and i want to take advantage of the fact that graphql allows us to select subset of fields. So i want to just query fields i need to optimize the query.

Now how would i go about that when implementing resolvers for example:

```graphql
query findTodos {
  todos {
    text
    done
  }
}
```

```go
func (r *TodoResolver) Query_todos(ctx context.Context) ([]Todo, error) {
    // how do i access which of the fields were selected in the query here
    rows, err := r.db.Query("SELECT text, done FROM todos")
}
```

Thank you for any pointers :) Keep up the great job!

**Comment by vektah** [comment]
Sorry, This isn't currently being exposed, but it will get added shortly for [Schema stitching](https://github.com/vektah/gqlgen/issues/5).

**Comment by jbub** [comment]
Thank you :)
