### ISSUE TITLE
With dgraph

### ISSUE THREAD

**Issue by gedw99** [vektah/gqlgen#3]
I wonder if this helps when working with dgraph ?

**Comment by vektah** [comment]
I'm not sure, what are you picturing?

I am thinking about schema stitching, which might let you attach parts of a dgraph (or grpc or twirp) to parts of your local app data.

**Comment by gedw99** [comment]
I see your point.

Funnily enough the query engine fro dgraph is called "CQL" like your
library is named.

Its really an awesome project.

I will try it out with dgraph !! They have a none standard graphql
implemenation:
https://github.com/dgraph-io/dgraph/issues/933

will let you knwo..
