### ISSUE TITLE
Question: Why not hard fork an existing library?

### ISSUE THREAD

**Issue by salmana1** [vektah/gqlgen#35]
Hey,

Thank you for your great work; this library has a lot of potential. Sorry, I am not sure where else to ask this question. I am curious to know why did you decide to create a new library. Why not just hard fork neelance's go library? 

At my work, we are using neelance's go library and even wrote our own [code generator](https://github.com/DealTap/graphql-gen-go). We are also looking at its internal code and has hard forked it to experiment changes (i.e., make internal code exportable, use fields as resolver instead of methods, access to requested fields, add missing security features etc)

**Comment by vektah** [comment]
This *is* a hard fork of the neelance library, I've reused the parsers and validation but code generated the execution environment. 

 I hope that https://github.com/neelance/graphql-go/issues/116 gets resolved and we can start collaborating.
