### ISSUE TITLE
ResolverError field in QueryError not set and public errors in general

### ISSUE THREAD

**Issue by dvic** [vektah/gqlgen#38]
I see that the `ResolverError` field on `QueryError` is not set. What is the plan for this? The `Builder` for errors currently only takes the error message and creates a `QueryError` from that.

I was a bit surprised to see that by default the generated execution context drops the original error and exposes the raw message error in the GraphQL response. What are your thoughts for this?

I can imagine one wants to be able to control how errors thrown from the resolvers are rendered. I'm using a custom written HTTP handler and would like to be able to log the original errors. Do you  think it's better to do logging etc. of the errors inside the resolvers and return a custom 'public' error?

Thanks for the awesome lib! Please let us know if there are any areas where you could use some help!

**Comment by vektah** [comment]
I guess you are expecting it to work a bit more like [this](https://github.com/graph-gophers/graphql-go/blob/1a11622ce658bdf2f7a63c80112d76e4794706ee/internal/exec/exec.go#L186-L189)?

It would let you put a String() method on your error for display to the user?

**Comment by dvic** [comment]
Yes exactly. Storing the `ResolverError` will at least allow us to recover the original error and log it in the http handler.  But I'm unsure how to best address the error rendering. What about checking whether the error implements
```
interface{ 
   PublicError() string
}
```
and use `PublicError()` as the error response message? Another option would be to pass a function `publicError(err string) string`(like `recoverPanicFn`) that extracts the error message.

Let me know what you think, I could try to make a PR for this once we decide what approach to go for.

**Comment by vektah** [comment]
> Another option would be to pass a function publicError(err string) string(like recoverPanicFn) that extracts the error message.

I really like this idea. Leave the error as an `error` until the very end and let the user decide. Provide a default that just does a `err.Error()` 

Its probably a fair bit of work though.

**Comment by dvic** [comment]
@vektah I gave it a first shot in #45. Is this something like you had in mind?
