### ISSUE TITLE
[feature]/event hook - Schema Directives

### ISSUE THREAD

**Issue by imiskolee** [vektah/gqlgen#39]
how to make authorzation layer when i generated a graphql server.
i think we need a event call before call each query/mutation.

for:

1.  authorization layer (Before* event)
2. access log (After* event)
3. common control logic

its like:

```go
type Event interface{
  BeforeQuery(ctx context.Context)
  BeforeEachQuery(ctx context.Context,opName string,opParams map[string]interface{})
  BeforeEachMutation(ctx context.Context,opName string,opParams map[string]interface{})
  AfterQuery(ctx context.Context)
  AfterEachQuery(ctx context.Context,opName string,opParams map[string]interface{},output interface{})
  AfterEachMutation(ctx context.Context,opName string,opParams map[string]interface{},output interface{})
} 
```

**Comment by gedw99** [comment]
sounds perfect to me too

**Comment by vektah** [comment]
I'm not a fan of `map[string]interface{}`.  I think what is really needed here is [schema directives](https://blog.graph.cool/graphql-directive-permissions-authorization-made-easy-54c076b5368e)

for example:
```graphql
directive @hasRole(role: String) on FIELD | FIELD_DEFINITION

type Mutation {
    updateAskingPrice(id: ID!, newPrice: Float!): Vehicle! @hasRole(role: "MANAGER")
}
```
could generate resolver methods
```go
func (r *Resolvers) Directive_Vehicle_hasRole(ctx context.Context, next func(ctx context.Context) *Vehicle, role string) *Vehicle {
    if !UserForCtx(ctx).HasRole(role) {
        return nil
    }
    return next(ctx)
}
```

**Comment by andrewmunro** [comment]
Agree with @vektah, directives are the way to go!

I'm also following progress on https://github.com/facebook/graphql/issues/300 to expose directives via introspection, that way the client can know what they have access to.

**Comment by imiskolee** [comment]
yes. i think directive better than.

i has some case for directive:

1. control for each mutation operator.
2. control for each field
3. mixed directive control(sorted of define)
4. change raw request
5. change raw response

@vektah  someone work on it ?

**Comment by vektah** [comment]
The blocker on this is that the parser gqlgen uses (https://github.com/graph-gophers/graphql-go/tree/master/internal/schema) doesn't currently support schema directives, only query directives.

@tonyghita has recently started maintaining it again and has been pushing the parser forward so I am reluctant to make too many changes here until we see which way he takes it. I think there was talk in the gophers slack around bringing in a new lexer which would be a pretty large change.

Good directive support is also required to validate against https://github.com/graphql-cats/graphql-cats

**Comment by vektah** [comment]
This has kinda progressed on two fronts, 

Firstly, most of the hooks described above can be achieved using middleware, I haven't documented it yet but take a look at the [opentracing](https://github.com/vektah/gqlgen/blob/master/opentracing/opentracing.go) for some ideas. 

Secondly, work on a [new parser](https://github.com/vektah/gqlparser) is well under way, currently working through setting up the validation logic in a way thats maintainable going forward. There was a bit of related chatter in #100

**Comment by vektah** [comment]
Closed in favour of https://github.com/vektah/gqlgen/issues/156
