### ISSUE TITLE
string ID types?

### ISSUE THREAD

**Issue by buchanae** [vektah/gqlgen#41]
Would it be possible to generate code using `string` as the underlying type of GQL ID? Currently it is generated as `int`, which is more cumbersome for my databases.

**Comment by vektah** [comment]
They should be already?

eg https://github.com/vektah/gqlgen/blob/master/example/chat/schema.graphql#L7
```graphql
type Message {
    id: ID!
    text: String!
    createdBy: String!
    createdAt: Time!
}
```

results in 
https://github.com/vektah/gqlgen/blob/master/example/chat/models_gen.go#L10
```go
type Message struct {
	ID        string
	Text      string
	CreatedBy string
	CreatedAt time.Time
}
```

**Comment by ereyes01** [comment]
Yes, as a matter of fact I was trying to do the opposite- use an int as the ID type in my own mapped type, but `gqlgen` fails with this error:

`type mismatch on Org.id, expected string got int`

But it looks like this is the correct behavior, according to the [graphql docs](http://graphql.org/learn/schema/#scalar-types):

> ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

**Comment by vektah** [comment]
You could define your own ID type if you want to use ints, see [the example](https://github.com/vektah/gqlgen/tree/master/example/scalars).
