### ISSUE TITLE
migrate to graph-gophers/graphql-go

### ISSUE THREAD

**Issue by dengliu** [vektah/gqlgen#58]
### migrate to graph-gophers/graphql-go
Hi @vektah , great job on making the code generator.
I wonder if you have plan to migrate you code to the new repo graph-gophers/graphql-go?
neelance/graphql-go (@neelance ) has been transferred to graph-gophers/graphql-go and @tonyghita  is actively working on and maintaining it.

**Comment by vektah** [comment]
gqlgen started as a fork of neelance/graphql-go, all of the code shared lives in `neelance` in the root directory.

I hope https://github.com/graph-gophers/graphql-go/issues/116 gets fixed I can delete the neelance directory and start pushing fixes upstream.

Until then, I'll need to cherry pick any fixes over.
