### ISSUE TITLE
Suggestion: Generate resolver for fields missing from go model

### ISSUE THREAD

**Issue by andrewmunro** [vektah/gqlgen#63]
When we first started using gqlgen, if your go model did not have a field publicly accessible that was specified on your schema, the generator would generate a resolver for you to manually handle it. 

```
// schema.graphql
schema {
	query: Query
}

type Query {
	cars: [Car]!
}

type Car {
	name: String
	model: String
	created:Time
	new: Boolean
}
```

```
// model.go
package model

type Car struct {
	Name    string    `db:"name"`
	Model   string    `db:"model"`
	Created time.Time `db:"created"`
}
```

```
// types.json
{
    "Car": "path/to/model.Car"
}
```

```
// generated.go
type Resolvers interface {
	Query_cars(ctx context.Context) ([]model.Car, error)
	Field_car_new(ctx context.Context, car model.Car) (bool, error) // This is missing
}
```

Unfortunately, this functionality disappeared when you introduced the model generator.
This was really nice feature if you have any fields on your graphql model that are generated by business logic. For the example above, something like:

```
// resolver.go
func (r *QueryResolver) Field_car_new(ctx context.Context, car model.Car) (bool, error) {
	weekAgo := time.Now().AddDate(0, -7, 0)
	return car.Created.After(weekAgo)
}
```

I can understand the answer is probably to separate db go models from graphql go models, but for an example like this where most of the fields are duplicated, I don't see it worth it for the added overhead and complexity.

**Comment by vektah** [comment]
This should still work the way you describe. Model generation only happens if you don't add the model to types.json.

eg, [the starwars example](https://github.com/vektah/gqlgen/blob/master/example/starwars/resolvers.go#L34) is still using it for the friends connection 

Whats probably happening is `types.json` isnt being searched for by default any more, you need to add a `-typemap types.json` if you want to map to your own types.

**Comment by andrewmunro** [comment]
@vektah No it is searching fine, we now receive an error:

```
unable to bind Car.new to anything, path/to/model.Car has no suitable fields or methods
```
If you add a `New` field to the `Car` model it fixes it.

Generating with the following:

`//go:generate gorunpkg github.com/vektah/gqlgen -package schema -schema schema.graphql -typemap types.json -out generated.go`

**Comment by vektah** [comment]
that was just a warning, but I've removed it to avoid future confusion.

Scalars has an example:
https://github.com/vektah/gqlgen/blob/master/example/scalars/resolvers.go#L49-L55 has an example

**Comment by Sparx2** [comment]
😶
