### ISSUE TITLE
Allow OPTIONS request for CORS-enabled servers

### ISSUE THREAD

**Issue by pkosiec** [vektah/gqlgen#68]
Hello @vektah, firstly I have to say that this library is awesome!

I've run into an issue with CORS enabled server using gqlgen. All `OPTIONS` requests from client fails (Bad request -`{“data”:null,“errors”:[{“message”:“json body could not be decoded: EOF”}]}`), because currently only `GET` and `POST` requests are supported.

```
		if r.Method == "GET" {
			...
		} else {

// Assumes that this is POST request

			if err := json.NewDecoder(r.Body).Decode(&reqParams); err != nil {
				sendErrorf(w, http.StatusBadRequest, "json body could not be decoded: "+err.Error())
				return
			}
		}
```

Can you please add `OPTIONS` request support?
Thank you very much in advance!

**Comment by vektah** [comment]
Why not use a piece of dedicated middleware for this? I'm quite partial to the chi stuff https://github.com/go-chi/cors/blob/master/cors.go

**Comment by pkosiec** [comment]
I'm already using it... But I see I probably screw this up by enabling OptionsPassthrough option in go-chi/cors library... I have to confirm this. Anyway thank you for quick response! I will let you know what I found

**Comment by pkosiec** [comment]
@vektah Yup, this was my fault. I've accidentally set `OptionsPassthrough` to true. Thank you with solving my issue!
Also, thanks for polishing the code in your newly created PR! You rock, man!
