### ISSUE TITLE
Generates enum that is listed in types.json

### ISSUE THREAD

**Issue by JonLundy** [vektah/gqlgen#71]
I added a custom enum type to types.json and use it in my graphql spec.

### Expected Behaviour

gqlgen would use the custom type instead of generating enum into models_gen.go

### Actual Behavior

enum code is generated into models_gen.go and a mismatch error is reported

```
type mismatch on Foo.state, expected <package>/foo.FooState got <package>/foo/custom.FooState
```
### Minimal graphql.schema and models to reproduce

graph.graphql:
```
type Query {
    foo(): Foo!
}

type Foo {
    state: FooState!
}

enum FooState {
    BIN
    BAR
    BAZ
}
```

types.json:
```
{
  "FooState": "<package>/foo/custom.FooState"
}
```
custom/foo.go:
```
package custom

import (
	"fmt"
	"io"
	"strconv"
)

type FooState string

const (
	FooStateBin FooState = "BIN"
	FooStateBar FooState = "BAR"
	FooStateBaz FooState = "BAZ"
)

func (e FooState) IsValid() bool {
	switch e {
	case FooStateBin, FooStateBar, FooStateBaz:
		return true
	}
	return false
}

func (e FooState) String() string {
	return string(e)
}

func (e *FooState) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FooState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FooState", str)
	}
	return nil
}

func (e FooState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
```

**Comment by JonLundy** [comment]
I have managed to work around this issue using the newly added -modelpackage flag so that it generates the enum into the same folder as my custom models

**Comment by vektah** [comment]
Thanks for the bug report, should be fixed now.

I updated model to take directory names so enums could live with the other models, otherwise you end up with import loops pretty quickly.

What was the reason you needed a custom enum? Is it common enough to be worth folding into the generated enum?

**Comment by JonLundy** [comment]
I was attempting to avoid import loops and keep my models together. The new flag for module dir is exactly what I needed. 

It looks like the module code is still using -package
