### ISSUE TITLE
Default Variables in Inputs aren't generated.

### ISSUE THREAD

**Issue by Teddy-Schmitz** [vektah/gqlgen#73]
### Expected Behaviour
Default variables are generated and used when declaring an input.
### Actual Behavior
Default variables aren't generated and are ignored.
### Minimal graphql.schema and models to reproduce
```
schema {
    query: Query
}

type Query {
    Test(input: DateFilter): Boolean
}

enum DATE_FILTER_OP {
    EQ
    NEQ
    GT
    GTE
    LT
    LTE
}

input DateFilter {
    value: String!
    timezone: String = "UTC"
    op: DATE_FILTER_OP!
}
```

snippet of model generated
```
type DateFilter struct {
	Value    string
	Timezone *string
	Op       DATE_FILTER_OP
}
```

**Comment by mmacheerpuppy** [comment]
Experiencing this issue on a build, @vektah should this be working?
