### ISSUE TITLE
aliased fields are omitted if non-alias field is defined in query

### ISSUE THREAD

**Issue by yamitzky** [vektah/gqlgen#83]
If non-alias field and alias fields are defined in a query, alias fields are unexpectedly omitted.

Here is a starwars example to reproduce.

```graphql
{
  reviews(episode: EMPIRE) {
    stars
  }
  jediReviews: reviews(episode: JEDI) {
    stars
  }
}
```

### Expected Behaviour

```json
{
  "data": {
    "reviews": [],
    "jediReviews": []
  }
}
```

### Actual Behavior

```json
{
  "data": {
    "reviews": []
  }
}
```

In addition to that, resolver for field `jediReviews` is never invoked.

**Comment by grzn** [comment]
#84 does not fix this.
The resolver for the alias is never invoked.

**Comment by grzn** [comment]
This issue should be re-opened.
