### ISSUE TITLE
Mutation with variables not working

### ISSUE THREAD

**Issue by rhymes** [vektah/gqlgen#85]
### Expected Behaviour

I would expect the following mutation to be working:

```json
{
  "query": "mutation createApp($app: AppInput!) {\\n  createApp(app: $app) {\\n}\\n}\\n",
  "variables": {
    "appID": "foobar"
  }
}
```

This is the body of the JSON mutation sent to gqlgen.

Unfortunately the actual "model" in the resolver has that field empty.

If the mutation is sent as:

```graphql
mutation createApp {
  createApp(app: {appID: "foobar"}) {
  }
}
```

then it works.

I debugged a bit and I noticed that in the first case the variables are in the context of the mutation:

```go
func (r *Resolver) Mutation_createApp(ctx context.Context, app models.App) (*models.App, error) { // nolint: golint
	reqContext := graphql.GetRequestContext(ctx)
	fmt.Println(reqContext.Variables)
	runtime.Breakpoint()

       # .....
}
```

this prints all the variables I sent using the client but the actual model struct is empty. With the second method there are no variables and the model struct is filled with the values.

Am I doing something wrong?

### Actual Behavior

I would expect the mutation to receive the struct filled with the variables sent on the wire. In the meantime I'm filling the model struct manually from the request context.

### Minimal graphql.schema and models to reproduce

```graphql
type Mutation {
    createApp(app: AppInput!): App
}

type App {
    appID: ID!
}

input AppInput {
    appID: ID!
}
```

and the model:

```go
type App struct {
	AppID                     string    `sql:",notnull" json:"appID"`
}
```

**Comment by vektah** [comment]
Your query is using $app, but your passing on appID as the variable

**Comment by vektah** [comment]
I wonder if adding an error for unused variables would break people's code.

**Comment by Teddy-Schmitz** [comment]
I dont think throwing an error for unused variables here is the way to go, unless its part of the graphql spec.  This is more like user error.

**Comment by vektah** [comment]
I don't see anything in [the spec](https://github.com/facebook/graphql/blob/master/spec/Section%205%20--%20Validation.md), but maybe it should be.

There is a bit of chatter in https://github.com/facebook/graphql/issues/235 regarding input field properties which is pretty close. Variables don't have the same issues regarding removing fields.

Either way it would probably need to be gated behind a strict mode flag.

**Comment by rhymes** [comment]
It works, thank you! I had to expand the uint32 unmarshaler because in interface{} ints are float64 but it works!
