### ISSUE TITLE
Feature - File Upload

### ISSUE THREAD

**Issue by imiskolee** [vektah/gqlgen#91]
Hi,All:

how to handle file upload in matation ?

**Comment by vektah** [comment]
We use a separate endpoint for file uploads. Browsers are expecting to POST a multipart form body with the file. Once the upload was successful you can refetch the file data from the server using a standard query, or subscribe to it first and get notified.

**Comment by imiskolee** [comment]
@vektah 
thanks! 

did you mean graphql level can't directly handle multi-form file upload ?

where define this behavior(can't support multi-form) ?
    graphQL spec  or  gqlgen

**Comment by vektah** [comment]
There is nothing in the graphql spec that talks about file uploads. There is a defacto standard in https://github.com/jaydenseric/apollo-upload-server that you could look at implementing but I would just step out of graphql for this

**Comment by vektah** [comment]
I'm going to close this out, I don't think it belongs in gqlgen because: 
 - its not in the spec
 - its not a super common use case (like Time)
 - it can be implemented as a separate package (and if it cant, lets talk about those issues).

**Comment by robert-zaremba** [comment]
There is a [spec](https://github.com/jaydenseric/graphql-multipart-request-spec) for this. Not sure what's the FB takke on this.  Apollo implements it:
https://www.apollographql.com/docs/guides/file-uploads.html

I think it would be good to have a default support in GraphQL rather than escaping to REST.
