### ISSUE TITLE
Need access to a particular HTTP request header in a resolver function

### ISSUE THREAD

**Issue by jayp** [vektah/gqlgen#98]
Resolver functions get `context.Context` but they don't seem to carry on the HTTP request header(s). I need access to only 1 specific header, but some other users may need more than 1.

I am considering submitting a PR that adds the ability to provide a new "`CarryHeader`" `Option` to `handler.GraphQL`. This will allow users to carry on values of specific headers to resolver functions via `graphql.RequestContext`.

Is this a reasonable way forward? Feedback appreciated.

**Comment by vektah** [comment]
The graph reaching back into the http request is jumping through too many levels of abstraction IMO. What if a non-http transport is used?

I would recommend putting the value you derive from the header into context using normal http middleware.

For example, turn your session cookie into a User object and put that into context:
```
func UserMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		user := findUserForRequest(r)
		ctx := SetContext(r.Context(), user)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```

**Comment by jayp** [comment]
Yes, this is more reasonable. Thank you for the quick feedback.
