### ISSUE TITLE
Flutter Client

### ISSUE THREAD

**Issue by gedw99** [vektah/gqlgen#99]
The readme with the comparison is really great btw.

I am working through how to get flutter talking to the graphql.
With Flutter you can do alot of codegen and so i am thinking though how best codegen the Dart code from the graphql schema. 

This looks like a really good library to base it on:
https://github.com/davidmarne/flutter_built_redux

i like his because it also allow to use the same code and code gen for Dat web also. Not many libs have this

Anyway, i am raising this here because there might be others working on this.

**Comment by vektah** [comment]
This feels a bit out of scope for gqlgen.

 if there is something needed to support it like extra introspection endpoints etc I would be happy to add something here. But I think most of this needs to happen client side.

https://github.com/apollographql/apollo-client/issues/2756 Apollo has an open issue maybe it's worth collaborating there?

**Comment by gedw99** [comment]
its is out of scope. I dont think it shoudl be in your repo at all.

Its more of a call out to anyone that wants to do it :)

Its a very good match.

The apollo Issue. I already did my minion +1. They have no responded to the
many +1's and so i figured its better to do it yourself.
